import Foundation

/// A local, offline list of quotes. No network access is required.
enum QuoteData {
    static let quotes: [Quote] = [
        Quote(id: 0, text: "The only way to do great work is to love what you do.", author: "Steve Jobs"),
        Quote(id: 1, text: "Life is what happens when you're busy making other plans.", author: "John Lennon"),
        Quote(id: 2, text: "It is during our darkest moments that we must focus to see the light.", author: "Aristotle"),
        Quote(id: 3, text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney"),
        Quote(id: 4, text: "Don't let yesterday take up too much of today.", author: "Will Rogers"),
        Quote(id: 5, text: "You learn more from failure than from success.", author: "Unknown"),
        Quote(id: 6, text: "If you are working on something exciting, it will keep you motivated.", author: "Steve Jobs"),
        Quote(id: 7, text: "Whether you think you can or you think you can't, you're right.", author: "Henry Ford"),
        Quote(id: 8, text: "The only impossible journey is the one you never begin.", author: "Tony Robbins"),
        Quote(id: 9, text: "In the middle of every difficulty lies opportunity.", author: "Albert Einstein"),
        Quote(id: 10, text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt"),
        Quote(id: 11, text: "It always seems impossible until it's done.", author: "Nelson Mandela"),
        Quote(id: 12, text: "Success is not final, failure is not fatal: it is the courage to continue that counts.", author: "Winston Churchill"),
        Quote(id: 13, text: "The future belongs to those who believe in the beauty of their dreams.", author: "Eleanor Roosevelt"),
        Quote(id: 14, text: "Do not wait to strike till the iron is hot, but make it hot by striking.", author: "William Butler Yeats"),
        Quote(id: 15, text: "Act as if what you do makes a difference. It does.", author: "William James"),
        Quote(id: 16, text: "Everything you've ever wanted is on the other side of fear.", author: "George Addair"),
        Quote(id: 17, text: "Hardships often prepare ordinary people for an extraordinary destiny.", author: "C.S. Lewis"),
        Quote(id: 18, text: "Just when the caterpillar thought the world was over, it became a butterfly.", author: "Proverb"),
        Quote(id: 19, text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
        Quote(id: 20, text: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington"),
        Quote(id: 21, text: "It does not matter how slowly you go as long as you do not stop.", author: "Confucius"),
        Quote(id: 22, text: "Everything has beauty, but not everyone can see it.", author: "Confucius"),
        Quote(id: 23, text: "Turn your wounds into wisdom.", author: "Oprah Winfrey"),
        Quote(id: 24, text: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
        Quote(id: 25, text: "Go confidently in the direction of your dreams. Live the life you have imagined.", author: "Henry David Thoreau"),
        Quote(id: 26, text: "When I let go of what I am, I become what I might be.", author: "Lao Tzu"),
        Quote(id: 27, text: "Happiness is not something ready-made. It comes from your own actions.", author: "Dalai Lama"),
        Quote(id: 28, text: "Twenty years from now you will be more disappointed by the things you didn't do.", author: "Mark Twain"),
        Quote(id: 29, text: "The best way to predict the future is to create it.", author: "Abraham Lincoln"),
        Quote(id: 30, text: "Life is 10% what happens to us and 90% how we react to it.", author: "Charles R. Swindoll"),
        Quote(id: 31, text: "The purpose of our lives is to be happy.", author: "Dalai Lama"),
        Quote(id: 32, text: "Get busy living or get busy dying.", author: "Stephen King"),
        Quote(id: 33, text: "You only live once, but if you do it right, once is enough.", author: "Mae West"),
        Quote(id: 34, text: "Many of life's failures are people who did not realize how close they were to success when they gave up.", author: "Thomas A. Edison"),
        Quote(id: 35, text: "If you want to live a happy life, tie it to a goal, not to people or things.", author: "Albert Einstein"),
        Quote(id: 36, text: "Never let the fear of striking out keep you from playing the game.", author: "Babe Ruth"),
        Quote(id: 37, text: "Money and success don't change people; they merely amplify what is already there.", author: "Will Smith"),
        Quote(id: 38, text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs"),
        Quote(id: 39, text: "Not how long, but how well you have lived is the main thing.", author: "Seneca"),
        Quote(id: 40, text: "If life were predictable it would cease to be life, and be without flavor.", author: "Eleanor Roosevelt"),
        Quote(id: 41, text: "The whole secret of a successful life is to find out what is one's destiny to do.", author: "Henry Ford"),
        Quote(id: 42, text: "In order to write about life first you must live it.", author: "Ernest Hemingway"),
        Quote(id: 43, text: "The big lesson in life, baby, is never be scared of anyone or anything.", author: "Frank Sinatra"),
        Quote(id: 44, text: "Life is a succession of lessons which must be lived to be understood.", author: "Ralph Waldo Emerson"),
        Quote(id: 45, text: "Life is what we make it, always has been, always will be.", author: "Grandma Moses"),
        Quote(id: 46, text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart"),
        Quote(id: 47, text: "Every strike brings me closer to the next home run.", author: "Babe Ruth"),
        Quote(id: 48, text: "Definiteness of purpose is the starting point of all achievement.", author: "W. Clement Stone"),
        Quote(id: 49, text: "We must balance conspicuous consumption with conscious capitalism.", author: "Kevin Kruse"),
        Quote(id: 50, text: "Life is not a problem to be solved, but a reality to be experienced.", author: "Søren Kierkegaard"),
        Quote(id: 51, text: "The most common way people give up their power is by thinking they don't have any.", author: "Alice Walker"),
        Quote(id: 52, text: "The mind is everything. What you think you become.", author: "Buddha"),
        Quote(id: 53, text: "The best time to plant a tree was 20 years ago. The second best time is now.", author: "Chinese Proverb"),
        Quote(id: 54, text: "An unexamined life is not worth living.", author: "Socrates"),
        Quote(id: 55, text: "Eighty percent of success is showing up.", author: "Woody Allen"),
        Quote(id: 56, text: "Your most unhappy customers are your greatest source of learning.", author: "Bill Gates"),
        Quote(id: 57, text: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas A. Edison"),
        Quote(id: 58, text: "A person who never made a mistake never tried anything new.", author: "Albert Einstein"),
        Quote(id: 59, text: "The only way to discover the limits of the possible is to go beyond them.", author: "Arthur C. Clarke"),
        Quote(id: 60, text: "Do what you can, with what you have, where you are.", author: "Theodore Roosevelt"),
        Quote(id: 61, text: "A little progress each day adds up to big results.", author: "Unknown"),
        Quote(id: 62, text: "Quality means doing it right when no one is looking.", author: "Henry Ford"),
        Quote(id: 63, text: "Simplicity is the ultimate sophistication.", author: "Leonardo da Vinci"),
        Quote(id: 64, text: "Well done is better than well said.", author: "Benjamin Franklin"),
        Quote(id: 65, text: "The journey of a thousand miles begins with one step.", author: "Lao Tzu"),
        Quote(id: 66, text: "Knowing yourself is the beginning of all wisdom.", author: "Aristotle"),
        Quote(id: 67, text: "Change your thoughts and you change your world.", author: "Norman Vincent Peale"),
        Quote(id: 68, text: "What we think, we become.", author: "Buddha"),
        Quote(id: 69, text: "The best revenge is massive success.", author: "Frank Sinatra"),
        Quote(id: 70, text: "Fall seven times and stand up eight.", author: "Japanese Proverb"),
        Quote(id: 71, text: "When you have a dream, you've got to grab it and never let go.", author: "Carol Burnett"),
        Quote(id: 72, text: "Nothing is impossible, the word itself says 'I'm possible'.", author: "Audrey Hepburn"),
        Quote(id: 73, text: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle"),
        Quote(id: 74, text: "Certain things catch your eye, but pursue only those that capture the heart.", author: "Ancient Indian Proverb"),
        Quote(id: 75, text: "Good things come to people who wait, but better things come to those who go out and get them.", author: "Unknown"),
        Quote(id: 76, text: "If you do what you always did, you will get what you always got.", author: "Unknown"),
        Quote(id: 77, text: "Success is walking from failure to failure with no loss of enthusiasm.", author: "Winston Churchill"),
        Quote(id: 78, text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
        Quote(id: 79, text: "What lies behind us and what lies before us are tiny matters compared to what lies within us.", author: "Ralph Waldo Emerson"),
        Quote(id: 80, text: "Keep your face always toward the sunshine, and shadows will fall behind you.", author: "Walt Whitman"),
        Quote(id: 81, text: "The struggle you're in today is developing the strength you need for tomorrow.", author: "Robert Tew"),
        Quote(id: 82, text: "You miss 100% of the shots you don't take.", author: "Wayne Gretzky"),
        Quote(id: 83, text: "I can't change the direction of the wind, but I can adjust my sails.", author: "Jimmy Dean"),
        Quote(id: 84, text: "It always seems impossible until it is done.", author: "Nelson Mandela"),
        Quote(id: 85, text: "Do one thing every day that scares you.", author: "Eleanor Roosevelt"),
        Quote(id: 86, text: "Dream big and dare to fail.", author: "Norman Vaughan"),
        Quote(id: 87, text: "What you get by achieving your goals is not as important as what you become.", author: "Zig Ziglar"),
        Quote(id: 88, text: "Start where you are. Use what you have. Do what you can.", author: "Arthur Ashe"),
        Quote(id: 89, text: "The only limit to our realization of tomorrow will be our doubts of today.", author: "Franklin D. Roosevelt"),
        Quote(id: 90, text: "You are never too old to set another goal or to dream a new dream.", author: "C.S. Lewis"),
        Quote(id: 91, text: "Little things make big days.", author: "Isabel Marant"),
        Quote(id: 92, text: "It's not whether you get knocked down, it's whether you get up.", author: "Vince Lombardi"),
        Quote(id: 93, text: "If you get tired, learn to rest, not to quit.", author: "Banksy"),
        Quote(id: 94, text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown"),
        Quote(id: 95, text: "Dream it. Wish it. Do it.", author: "Unknown"),
        Quote(id: 96, text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown"),
        Quote(id: 97, text: "Great things never come from comfort zones.", author: "Unknown"),
        Quote(id: 98, text: "Push yourself, because no one else is going to do it for you.", author: "Unknown"),
        Quote(id: 99, text: "Sometimes later becomes never. Do it now.", author: "Unknown"),
    ]
}
