// Demo-mode seed data. Used whenever Supabase isn't configured yet, so the
// prototype is fully clickable out of the box. See supabase-client.js.

export const MOCK_PROFILES = {
	'seller-aria': {
		id: 'seller-aria',
		username: 'aria.scents',
		display_name: 'Aria M.',
		location: 'Los Angeles, CA',
		bio: 'Collector of 8 years. Everything stored away from light/heat. Ships within 2 days.',
	},
	'seller-devon': {
		id: 'seller-devon',
		username: 'devon_niche',
		display_name: 'Devon K.',
		location: 'Austin, TX',
		bio: 'Downsizing my niche collection. Authenticity guaranteed, batch codes on request.',
	},
	'seller-mira': {
		id: 'seller-mira',
		username: 'mira.decants',
		display_name: 'Mira P.',
		location: 'Brooklyn, NY',
		bio: 'Selling a few bottles that just aren’t my scent profile anymore.',
	},
	'seller-owen': {
		id: 'seller-owen',
		username: 'owen.vault',
		display_name: 'Owen R.',
		location: 'Chicago, IL',
		bio: 'Occasional flips from a rotating collection. Fast, careful shipping.',
	},
};

export const MOCK_LISTINGS = [
	{
		id: 'l1',
		seller_id: 'seller-aria',
		brand: 'Dior',
		name: 'Sauvage EDP',
		gender: 'men',
		scent_family: ['spicy', 'woody', 'ambroxan'],
		size_ml: 100,
		fill_percentage: 85,
		condition: 'like_new',
		box_included: 'yes',
		batch_code: '2K01',
		purchase_year: 2023,
		price: 79,
		description: 'Bought as a gift, wore it twice and it’s just not for me. Stored upright in original box, away from sunlight.',
		images: ['🧴'],
		status: 'available',
		created_at: '2026-07-20T10:00:00Z',
	},
	{
		id: 'l2',
		seller_id: 'seller-devon',
		brand: 'Chanel',
		name: 'Bleu de Chanel Parfum',
		gender: 'men',
		scent_family: ['citrus', 'woody', 'aromatic'],
		size_ml: 100,
		fill_percentage: 60,
		condition: 'gently_used',
		box_included: 'yes',
		batch_code: '5015',
		purchase_year: 2022,
		price: 95,
		description: 'One of my favorites but I have a backup. Fill level measured with a scale, photo of the actual bottle available on request.',
		images: ['🍶'],
		status: 'available',
		created_at: '2026-07-22T10:00:00Z',
	},
	{
		id: 'l3',
		seller_id: 'seller-mira',
		brand: 'Yves Saint Laurent',
		name: 'Black Opium EDP',
		gender: 'women',
		scent_family: ['vanilla', 'coffee', 'floral'],
		size_ml: 90,
		fill_percentage: 70,
		condition: 'gently_used',
		box_included: 'no',
		batch_code: '3A02',
		purchase_year: 2023,
		price: 55,
		description: 'Lost the box in a move but the bottle is in great shape. Smells incredible for fall/winter.',
		images: ['🌸'],
		status: 'available',
		created_at: '2026-07-18T10:00:00Z',
	},
	{
		id: 'l4',
		seller_id: 'seller-owen',
		brand: 'Tom Ford',
		name: 'Oud Wood',
		gender: 'unisex',
		scent_family: ['oud', 'sandalwood', 'spice'],
		size_ml: 50,
		fill_percentage: 90,
		condition: 'new',
		box_included: 'yes',
		batch_code: '4G21',
		purchase_year: 2025,
		price: 180,
		description: 'Never used, cellophane removed to check batch code only. Comes with receipt.',
		images: ['✨'],
		status: 'available',
		created_at: '2026-07-27T10:00:00Z',
	},
	{
		id: 'l5',
		seller_id: 'seller-aria',
		brand: 'Creed',
		name: 'Aventus',
		gender: 'men',
		scent_family: ['pineapple', 'birch', 'smoky'],
		size_ml: 100,
		fill_percentage: 45,
		condition: 'well_used',
		box_included: 'no',
		batch_code: '21X01',
		purchase_year: 2021,
		price: 220,
		description: 'Popular batch, very fruity opening. Priced per remaining ml. Happy to send a spray sample first.',
		images: ['🍍'],
		status: 'available',
		created_at: '2026-07-15T10:00:00Z',
	},
	{
		id: 'l6',
		seller_id: 'seller-devon',
		brand: 'Jo Malone',
		name: 'Wood Sage & Sea Salt Cologne',
		gender: 'unisex',
		scent_family: ['sea salt', 'sage', 'ambrette'],
		size_ml: 100,
		fill_percentage: 80,
		condition: 'like_new',
		box_included: 'yes',
		batch_code: '19B4',
		purchase_year: 2024,
		price: 60,
		description: 'Clean, airy scent — great for everyday wear. Barely used.',
		images: ['🌊'],
		status: 'available',
		created_at: '2026-07-24T10:00:00Z',
	},
	{
		id: 'l7',
		seller_id: 'seller-mira',
		brand: 'Maison Margiela',
		name: 'Replica Jazz Club',
		gender: 'unisex',
		scent_family: ['rum', 'tobacco', 'vanilla'],
		size_ml: 100,
		fill_percentage: 55,
		condition: 'gently_used',
		box_included: 'damaged',
		batch_code: '7C19',
		purchase_year: 2022,
		price: 65,
		description: 'Box has some water damage but the bottle itself is perfect. Cozy, smoky scent.',
		images: ['🥃'],
		status: 'sold',
		created_at: '2026-07-10T10:00:00Z',
	},
	{
		id: 'l8',
		seller_id: 'seller-owen',
		brand: 'Byredo',
		name: 'Gypsy Water',
		gender: 'unisex',
		scent_family: ['juniper', 'bergamot', 'vanilla'],
		size_ml: 50,
		fill_percentage: 95,
		condition: 'new',
		box_included: 'yes',
		batch_code: '88H3',
		purchase_year: 2025,
		price: 110,
		description: 'Duplicate gift, still sealed with sticker intact.',
		images: ['🌲'],
		status: 'available',
		created_at: '2026-07-28T10:00:00Z',
	},
];
